from flask import Flask, request, jsonify
import requests

app = Flask(__name__)

GEMINI_API_KEY = "   "  # Put this in Railway ENV VARS

GEMINI_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent"

@app.route("/get_fix", methods=["POST"])
def get_fix():
    data = request.json
    error = data.get("error", "")
    code = data.get("code", "")

    prompt = f"""You are a Lua expert helping debug Roblox code.
Here is a Lua error message:
{error}

Here is the related Lua code:
{code}

Suggest a fix for this issue, including an improved code snippet and a short explanation."""

    headers = {
        "Content-Type": "application/json"
    }

    payload = {
        "contents": [{
            "parts": [{
                "text": prompt
            }]
        }],
        "generationConfig": {
            "temperature": 0.7
        }
    }

    gemini_response = requests.post(
        GEMINI_URL + f"?key={GEMINI_API_KEY}",
        headers=headers,
        json=payload
    )

    if gemini_response.status_code == 200:
        result = gemini_response.json()
        text = result['candidates'][0]['content']['parts'][0]['text']
        return jsonify({
            "fix": text,
            "explanation": "Generated by Gemini"
        })
    else:
        return jsonify({
            "error": "Gemini API failed",
            "details": gemini_response.text
        }), 500

@app.route("/", methods=["GET"])
def home():
    return "Gemini AI API is running."

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=3000)
